export const FETCH_CHARACTERS_REQUEST = "FETCH_CHARACTERS_REQUEST";
export const FETCH_CHARACTER_PAGE_REQUEST = "FETCH_CHARACTER_PAGE_REQUEST";

export const FETCH_EPISODES_REQUEST = "FETCH_EPISODES_REQUEST";