export const SET_CHARACTERS_REQUEST = "SET_CHARACTERS_REQUEST";
export const SET_CHARACTERS_SUCCESS = "SET_CHARACTERS_SUCCESS";
export const SET_CHARACTERS_FAILED = "SET_CHARACTERS_FAILED";

export const SET_EPISODES_REQUEST = "SET_EPISODES_REQUEST";
export const SET_EPISODES_SUCCESS = "SET_EPISODES_SUCCESS";
export const SET_EPISODES_FAILED = "SET_EPISODES_FAILED";